version: '3'

services:
  graphhopper:
    build:
      context: ../graphoppertp
      dockerfile: ../graphoppertp/Dockerfile
    ports:
      - "8989:8989"
      - "8990:8990"
    networks:
      - tp-network

  backendtp:
    build:
      context: ../backend-tp
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - tp-network
    volumes:
      - ../backend-tp:/app

  angular:
    build:
      context: ../TP-1
      dockerfile: ../TP-1/Dockerfile
    ports:
      - "8080:80"
    networks:
      - tp-network
    volumes:
      - ../TP-1:/app


networks:
  tp-network:
    driver: bridge
