version: '3'

services:
  graphhopper:
    build:
      context: ../graphhopper
      dockerfile: ../graphhopper/Dockerfile
    ports:
      - "8989:8989"
      - "8990:8990"
    networks:
      - tp-network

  backendtp:
    build:
      context: ../TP-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - tp-network

  angular:
    build:
      context: ../TP-1
      dockerfile: ../TP-1/Dockerfile
    ports:
      - "8080:80"
    networks:
      - tp-network

networks:
  tp-network:
    driver: bridge
